<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ItemTest</name>
   <tag></tag>
   <elementGuidId>3e9cc6ca-1bac-4293-8a1b-0eead640b4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;results-container&quot;]/div[2]/gm-product-list[2]/div/div/a/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;results-container&quot;]/div[2]/gm-product-list[2]/div/div/a/div[2]/p</value>
   </webElementProperties>
</WebElementEntity>
